create table instrument_takes (
	student_id int NOT NULL REFERENCES student,
	instrument_uses int
);

insert into instrument_takes (student_id, instrument_uses) values (1, 1);
insert into instrument_takes (student_id, instrument_uses) values (2, 2);
insert into instrument_takes (student_id, instrument_uses) values (3, 2);
insert into instrument_takes (student_id, instrument_uses) values (4, 2);
insert into instrument_takes (student_id, instrument_uses) values (5, 1);
insert into instrument_takes (student_id, instrument_uses) values (6, 2);
insert into instrument_takes (student_id, instrument_uses) values (7, 2);
insert into instrument_takes (student_id, instrument_uses) values (8, 2);
insert into instrument_takes (student_id, instrument_uses) values (9, 1);
insert into instrument_takes (student_id, instrument_uses) values (10, 2);
insert into instrument_takes (student_id, instrument_uses) values (11, 2);
insert into instrument_takes (student_id, instrument_uses) values (12, 2);
insert into instrument_takes (student_id, instrument_uses) values (13, 2);
insert into instrument_takes (student_id, instrument_uses) values (14, 2);
insert into instrument_takes (student_id, instrument_uses) values (15, 2);
insert into instrument_takes (student_id, instrument_uses) values (16, 1);
insert into instrument_takes (student_id, instrument_uses) values (17, 1);
insert into instrument_takes (student_id, instrument_uses) values (18, 1);
insert into instrument_takes (student_id, instrument_uses) values (19, 2);
insert into instrument_takes (student_id, instrument_uses) values (20, 1);
insert into instrument_takes (student_id, instrument_uses) values (21, 1);
insert into instrument_takes (student_id, instrument_uses) values (22, 2);
insert into instrument_takes (student_id, instrument_uses) values (23, 2);
insert into instrument_takes (student_id, instrument_uses) values (24, 1);
insert into instrument_takes (student_id, instrument_uses) values (25, 1);
insert into instrument_takes (student_id, instrument_uses) values (26, 1);
insert into instrument_takes (student_id, instrument_uses) values (27, 1);
insert into instrument_takes (student_id, instrument_uses) values (28, 1);
insert into instrument_takes (student_id, instrument_uses) values (29, 2);
insert into instrument_takes (student_id, instrument_uses) values (30, 1);
insert into instrument_takes (student_id, instrument_uses) values (31, 1);
insert into instrument_takes (student_id, instrument_uses) values (32, 1);
insert into instrument_takes (student_id, instrument_uses) values (33, 1);
insert into instrument_takes (student_id, instrument_uses) values (34, 1);
insert into instrument_takes (student_id, instrument_uses) values (35, 2);
insert into instrument_takes (student_id, instrument_uses) values (36, 2);
insert into instrument_takes (student_id, instrument_uses) values (37, 1);
insert into instrument_takes (student_id, instrument_uses) values (38, 2);
insert into instrument_takes (student_id, instrument_uses) values (39, 1);
insert into instrument_takes (student_id, instrument_uses) values (40, 2);
insert into instrument_takes (student_id, instrument_uses) values (41, 1);
insert into instrument_takes (student_id, instrument_uses) values (42, 1);
insert into instrument_takes (student_id, instrument_uses) values (43, 2);
insert into instrument_takes (student_id, instrument_uses) values (44, 2);
insert into instrument_takes (student_id, instrument_uses) values (45, 1);
insert into instrument_takes (student_id, instrument_uses) values (46, 2);
insert into instrument_takes (student_id, instrument_uses) values (47, 2);
insert into instrument_takes (student_id, instrument_uses) values (48, 1);
insert into instrument_takes (student_id, instrument_uses) values (49, 2);
insert into instrument_takes (student_id, instrument_uses) values (50, 2);
