create table lesson_teaches (
	instructor_id int NOT NULL REFERENCES instructor,
	lesson_id int NOT NULL REFERENCES lesson
);

insert into lesson_teaches (instructor_id, lesson_id) values (8, 25);
insert into lesson_teaches (instructor_id, lesson_id) values (5, 38);
insert into lesson_teaches (instructor_id, lesson_id) values (42, 38);
insert into lesson_teaches (instructor_id, lesson_id) values (9, 9);
insert into lesson_teaches (instructor_id, lesson_id) values (49, 19);
insert into lesson_teaches (instructor_id, lesson_id) values (49, 26);
insert into lesson_teaches (instructor_id, lesson_id) values (33, 40);
insert into lesson_teaches (instructor_id, lesson_id) values (45, 8);
insert into lesson_teaches (instructor_id, lesson_id) values (13, 38);
insert into lesson_teaches (instructor_id, lesson_id) values (20, 49);
insert into lesson_teaches (instructor_id, lesson_id) values (22, 24);
insert into lesson_teaches (instructor_id, lesson_id) values (42, 7);
insert into lesson_teaches (instructor_id, lesson_id) values (21, 13);
insert into lesson_teaches (instructor_id, lesson_id) values (36, 48);
insert into lesson_teaches (instructor_id, lesson_id) values (7, 49);
insert into lesson_teaches (instructor_id, lesson_id) values (36, 17);
insert into lesson_teaches (instructor_id, lesson_id) values (19, 41);
insert into lesson_teaches (instructor_id, lesson_id) values (29, 12);
insert into lesson_teaches (instructor_id, lesson_id) values (46, 21);
insert into lesson_teaches (instructor_id, lesson_id) values (34, 18);
insert into lesson_teaches (instructor_id, lesson_id) values (50, 7);
insert into lesson_teaches (instructor_id, lesson_id) values (13, 4);
insert into lesson_teaches (instructor_id, lesson_id) values (5, 18);
insert into lesson_teaches (instructor_id, lesson_id) values (29, 1);
insert into lesson_teaches (instructor_id, lesson_id) values (30, 3);
insert into lesson_teaches (instructor_id, lesson_id) values (17, 31);
insert into lesson_teaches (instructor_id, lesson_id) values (15, 50);
insert into lesson_teaches (instructor_id, lesson_id) values (14, 4);
insert into lesson_teaches (instructor_id, lesson_id) values (18, 19);
insert into lesson_teaches (instructor_id, lesson_id) values (12, 44);
insert into lesson_teaches (instructor_id, lesson_id) values (24, 36);
insert into lesson_teaches (instructor_id, lesson_id) values (9, 45);
insert into lesson_teaches (instructor_id, lesson_id) values (23, 12);
insert into lesson_teaches (instructor_id, lesson_id) values (35, 22);
insert into lesson_teaches (instructor_id, lesson_id) values (22, 29);
insert into lesson_teaches (instructor_id, lesson_id) values (42, 42);
insert into lesson_teaches (instructor_id, lesson_id) values (33, 19);
insert into lesson_teaches (instructor_id, lesson_id) values (39, 41);
insert into lesson_teaches (instructor_id, lesson_id) values (24, 3);
insert into lesson_teaches (instructor_id, lesson_id) values (2, 28);
insert into lesson_teaches (instructor_id, lesson_id) values (4, 46);
insert into lesson_teaches (instructor_id, lesson_id) values (44, 46);
insert into lesson_teaches (instructor_id, lesson_id) values (27, 17);
insert into lesson_teaches (instructor_id, lesson_id) values (17, 19);
insert into lesson_teaches (instructor_id, lesson_id) values (9, 4);
insert into lesson_teaches (instructor_id, lesson_id) values (50, 19);
insert into lesson_teaches (instructor_id, lesson_id) values (49, 25);
insert into lesson_teaches (instructor_id, lesson_id) values (11, 28);
insert into lesson_teaches (instructor_id, lesson_id) values (18, 14);
insert into lesson_teaches (instructor_id, lesson_id) values (1, 22);
